version: 0.0
os: linux
files:
  - source: hello-angular/index.html
    destination: /var/www/html
    overwrite: yes
hooks:
  BeforeInstall:
    - location: hello-angular/scripts/remove.sh   
  AfterInstall:
    - location: hello-angular/scripts/restart_server.sh
    
