version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "sampleangular1245"
        BUILD_FOLDER: "dist"
       
phases:
  install:
    runtime-versions:
        nodejs: 12
        
  build:
     commands:
       - echo "${CODEBUILD_BUILD_ARN}"
       - |
         if expr "${CODEBUILD_BUILD_ARN}" : ".*build/Angular-demo1"; then
           sed -i 's/^destination: .*$/destination: /var/www/dev/' .ignore
         fi
       - |
         if expr "${CODEBUILD_BUILD_ARN}" : ".*build/MyProject-" >/dev/null; then
           echo "Not found"
         fi
       - cat appspec.yml
     
               
         
  #build:
   # commands:
    #    - echo lint started
        #- ng lint
     #   - echo build started
      #  - ng build
       # - echo testing started
        #- ng test -- --browsers=ChromeHeadlessCI
  #post_build:      
    #commands: |
    
       # if [ "$CODEBUILD_BUILD_SUCCEEDING" == "1" ]; then
        #echo "Uploading Artifacts to S3"
        #aws s3 cp dist s3://${S3_BUCKET}/$CODEBUILD_BUILD_NUMBER --recursive
        #fi
        #echo "Error in Unit Test"
        #- cd hihello
        #- whereis hihello
        #- pwd   
        #- ls -a
        #- zip -r codebuild.zip dist
        #- mv codebuild.zip $CODEBUILD_BUILD_NUMBER.zip
   #     - cp -r scripts dist/hello-angular/
    #    - cp appspec.yml dist/hello-angular/
     #   - mkdir codebuild
      #  - cp -r dist/hello-angular/* codebuild
        #- zip -r codebuild.zip codebuild/*
       # - ls -a
        #- zip -r -j $CODEBUILD_BUILD_NUMBER.zip codebuild/*
        #- ls -a
        #- aws s3 cp $CODEBUILD_BUILD_NUMBER.zip s3://${S3_BUCKET}/$CODEBUILD_BUILD_NUMBER.zip 
      
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
