version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "sampleangular1245"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 12
  pre_build:
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
        - TIME=$(date +"%Y%m%d_%H%M%S")
  build:
    commands:
        - echo Build started
        - ng build
       
        
  post_build:
    commands:
      - cd dist
      - zip -r ${TIME}.zip .      
      - echo "Uploading dist folder to s3"
      - aws s3 cp {TIME}.zip s3://${S3_BUCKET}/${TIME}.zip --recursive
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
