version: 0.2
env:
  variables:
    S3_BUCKET: "sampleangular1245"
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
      - echo "Get current timestamp for the reports naming"
      - TIME= $(date + "%Y%m%d_%H%M%S")
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod --aot
  post_build:
     commands:      
      - aws s3 cp dist s3://${S3_BUCKET}/%BUILD_ID/${TIME} --recursive
      - echo Build completed on `date`
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
