version: 0.2
env:
  variables:
    S3_BUCKET: "sampleangular1245"
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod --aot
  post_build:
     commands:
      - current_timestamp=$(date)
      - aws s3 cp dist s3://${S3_BUCKET}/build1/${current_timestamp} --recursive
      - echo Build completed on `date`
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
